// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqhOCESumAe2zIOR7U2wVJnhZeQp8JzQ',
    appId: '1:968903598520:web:bb16dd66ce7dd1bb706f4d',
    messagingSenderId: '968903598520',
    projectId: 'flutter-shared-preferences',
    authDomain: 'flutter-shared-preferences.firebaseapp.com',
    storageBucket: 'flutter-shared-preferences.appspot.com',
    measurementId: 'G-RQYM1LFLVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5SvHW0Q1tsegGTZvdHvX9Irmo1qCDXUg',
    appId: '1:968903598520:android:bb3c2965b61460bc706f4d',
    messagingSenderId: '968903598520',
    projectId: 'flutter-shared-preferences',
    storageBucket: 'flutter-shared-preferences.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMvVIDoBplHAAYOkAdDfff1203caD4ebM',
    appId: '1:968903598520:ios:495a98ebafafbb7d706f4d',
    messagingSenderId: '968903598520',
    projectId: 'flutter-shared-preferences',
    storageBucket: 'flutter-shared-preferences.appspot.com',
    iosBundleId: 'com.example.sharedPreferencesPackageFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMvVIDoBplHAAYOkAdDfff1203caD4ebM',
    appId: '1:968903598520:ios:f037242ae2f3ae2e706f4d',
    messagingSenderId: '968903598520',
    projectId: 'flutter-shared-preferences',
    storageBucket: 'flutter-shared-preferences.appspot.com',
    iosBundleId: 'com.example.sharedPreferencesPackageFlutter.RunnerTests',
  );
}
